# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

matrix:
  fast_finish: true
  
  include:
    - name: Xenial (g++-5)
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-5 && CXX=g++-5"

    - name: Xenial (g++-6)
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-6
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-6 && CXX=g++-6"

    - name: Xenial (g++-7)
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-7
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-7 && CXX=g++-7"

    - name: Xenial (g++-8)
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-8
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - COMPILERS="CC=gcc-8 && CXX=g++-8"

    - name: Xenial (clang++-3.7)
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
      compiler: clang

    - name: Xenial (clang++-3.8)
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
      compiler: clang

    - name: Xenial (clang++-3.9)
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
      compiler: clang

    - name: Xenial (clang++-4.0)
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      compiler: clang

    - name: Xenial (clang++-5.0)
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      compiler: clang

    - name: Xenial (clang++-6.0)
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libstdc++-6-dev
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      compiler: clang

    - name: Xenial (clang++-7.0)
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
      compiler: clang

    # OSX begin
    - name: Xcode10 (gcc++-5)
      os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages:
          - gcc@5
          - cmake
          update: true
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5

    - name: Xcode10 (gcc++-6)
      os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages:
          - gcc@6
          - cmake
          update: true
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6

    - name: Xcode10 (gcc++-7)
      os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages:
          - gcc@7
          - cmake
          update: true
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7

    - name: Xcode10 (gcc++-8)
      os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages:
          - gcc@8
          - cmake
          update: true
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8

before_install:
  # Overwrite default CC and CXX
  - eval "${COMPILERS}"

script:
  - cmake .
  - make
  - ./benchmark